spring.application.name=situation-service
spring.threads.virtual.enabled=true
server.port=8092

spring.neo4j.uri=${NEO4J_URI:neo4j://localhost:7687}
spring.neo4j.authentication.username=${NEO4J_USER:neo4j}
spring.neo4j.authentication.password=${NEO4J_PASSWORD:password}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=health,prometheus
management.endpoint.prometheus.access=unrestricted
