rootProject.name = "backend"
include("auth-service")
include("chat-service")
include("gateway-service")
include("eureka-server")
include("user-service")
include("llm-brain-service")
include("workspace-service")
include("graphs-service")
include("voice-service")
include("template-service")
include("law-service")
include("situation-service")
include("document-service")
