spring.application.name=document-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/documentsdb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.flyway.enabled=false

server.port=8093
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.embedding.transformer.onnx.model-uri=https://media.githubusercontent.com/media/spring-projects/spring-ai/refs/heads/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/model.onnx
spring.ai.embedding.transformer.onnx.tokenizer-uri=https://raw.githubusercontent.com/spring-projects/spring-ai/main/models/spring-ai-transformers/src/main/resources/onnx/all-MiniLM-L6-v2/tokenizer.json
spring.ai.embedding.transformer.resource-cache-dir=/app/embeddings-cache
spring.ai.embedding.transformer.onnx.resource.device=CPU

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB

app.storage.minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
app.storage.minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
app.storage.minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
app.storage.minio.bucket=${MINIO_BUCKET:user-documents}
