spring:
  application:
    name: graphs-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URI:http://localhost:9200}
  neo4j:
    uri: ${NEO4J_URI:neo4j://localhost:7687}
    authentication:
      username: ${NEO4J_USER:neo4j}
      password: ${NEO4J_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8086
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    com.jvmd: DEBUG
    org.springframework.data.neo4j: DEBUG

dms:
  base-url: ${DMS_BASE_URL:http://law-service:8087}

parser:
  skip-expired: true
  kz:
    base-url: https://zan.gov.kz
    search-path: /api/documents/search
